# Generated by Django 5.1.1 on 2024-10-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidad',
            name='comentario',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='apellido1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido1'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='apellido2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido2'),
        ),
    ]
