# Generated by Django 5.1.1 on 2024-10-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0002_habilidad_comentario_alter_personal_apellido1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ap1', models.CharField(max_length=100)),
                ('ap2', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
