# Generated by Django 3.2 on 2024-10-31 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appportfolio', '0003_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrevistador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Avatar')),
                ('empresa', models.CharField(blank=True, max_length=30, null=True, verbose_name='Empresa')),
                ('fecha_entrevista', models.DateField(blank=True, null=True, verbose_name='Fecha Entrevista')),
                ('conectado', models.BooleanField(blank=True, null=True, verbose_name='Conectado')),
                ('seleccionado', models.BooleanField(blank=True, null=True, verbose_name='Seleccionado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrevista_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrevistador',
                'verbose_name_plural': 'Entrevistadores',
                'ordering': ['empresa'],
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen del Diploma')),
                ('comentario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.FileField(blank=True, null=True, upload_to='video/', verbose_name='Video')),
                ('comentario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.AddField(
            model_name='personal',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='datos_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
