# Generated by Django 4.1.5 on 2024-11-29 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0010_estado_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('R', 'Realizado'), ('E', 'Empezando')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='estado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appportfolio.estado'),
        ),
    ]
