# Generated by Django 4.1.5 on 2024-12-02 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0015_alter_detallecurriculumexperiencia_experiencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'ordering': ['id'], 'verbose_name': 'Curriculum', 'verbose_name_plural': 'Curriculums'},
        ),
        migrations.AlterModelOptions(
            name='detallecurriculumestudio',
            options={'ordering': ['id'], 'verbose_name': 'DetalleCurriculumEstudio', 'verbose_name_plural': 'DetalleCurriculumEstudios'},
        ),
        migrations.AlterModelOptions(
            name='detallecurriculumexperiencia',
            options={'ordering': ['id'], 'verbose_name': 'DetalleCurriculumExperiencia', 'verbose_name_plural': 'DetalleCurriculumExperiencias'},
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='ap1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido1'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='ap2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido2'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='detallecurriculumestudio',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_detalle', to='appportfolio.curriculum'),
        ),
        migrations.AlterField(
            model_name='detallecurriculumestudio',
            name='estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estudio_detalle', to='appportfolio.estudio'),
        ),
        migrations.AlterField(
            model_name='detallecurriculumexperiencia',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_detalles', to='appportfolio.curriculum'),
        ),
        migrations.AlterField(
            model_name='detallecurriculumexperiencia',
            name='experiencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiencia_detalle', to='appportfolio.experiencia'),
        ),
    ]
