# Generated by Django 4.1.5 on 2024-12-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0017_alter_tarea_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asignatura', models.CharField(max_length=200)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Calificacion',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['id'],
            },
        ),
    ]
