# Generated by Django 4.1.5 on 2024-12-04 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0018_calificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['id'], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['id'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['id'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['id'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AlterModelOptions(
            name='valoracion',
            options={'ordering': ['id'], 'verbose_name': 'Valoracion', 'verbose_name_plural': 'Valoraciones'},
        ),
    ]
