# Generated by Django 4.1.5 on 2024-12-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0019_alter_estado_options_alter_mensaje_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('lenguaje', models.CharField(max_length=100)),
                ('tecnologias', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateField()),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['id'],
            },
        ),
    ]
